server:
  port: 3000

db:
  type: 'postgres'
  port: 5432

jwt:
  expiresIn: 3600
  secret: 'yinka0136'

cloudinary:
  cloud_name: 'yinka-tech'
  api_key: '427183122298698'
  secret: 'gA8pHGnKsTbow_Q4t-IezbXF-HE'
