db:
  host: 'ec2-52-21-153-207.compute-1.amazonaws.com'
  username: 'dirgmmlehiemqp'
  password: '0a206ed996a16898aee3634ce7aeedc8092ecf7ea8812e628dc4c88d39717f69'
  database: 'dju71gktk025q'
  synchronize: true
  ssl: false
  extra:
    ssl:
      rejectUnauthorized: false
