db:
  host: 'ec2-54-167-168-52.compute-1.amazonaws.com'
  username: 'zxchndrkhxiuwq'
  password: 'a0d47a29b67805a9b0cf83cea7c41a6dc6bf1302d337a9fefa5badf9df563090'
  database: 'd64b6oo613uvvc'
  synchronize: false
  ssl: true
  extra:
    ssl:
      rejectUnauthorized: false
